baseURL = "https://vmware-tanzu.github.io/rotate-instance-identity-certificates"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Rotate Instance Identity Certificates Docs"
theme = "learn"

[params]
    editURL = "https://github.com/vmware-tanzu/rotate-instance-identity-certificates/edit/main/docs/riic-docs/content"
    decription = "Tooling to rotate the Diego Instance Identity Certificates on TAS 2.4, 2.5, and 2.6."
    author = "VMware Tanzu"
        
    themeVariant = "blue"
    canonifyURLs = true
    disableLandingPageButton = true # it links to / and gh-pages puts us on a /path
    disableSearch = true
    showVisitedLinks = true
    disableMermaid = true
